version: 0.0
os: linux
files:
  - source: gdgocinha-fe/
    destination: /home/ubuntu/gdgocinha-fe
    overwrite: true
    mode: 0644
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: gdgocinha-fe/deploy.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: gdgocinha-fe/deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: gdgocinha-fe/deploy.sh
      timeout: 300
      runas: root
