version: "3.8"

services:
  frontend:
    image: "${DOCKER_HUB_USERNAME}/gdgoc-fe-app:latest"
    container_name: gdgoc-fe-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app  # 코드 변경 사항을 반영하려면 필요
    working_dir: /app
    command: "npm run start"

