export const users = [
  {
    member: {
      id: 1,
      name: "김소연",
      grade: 4,
      studentId: 12212444,
      phoneNumber: "010-1234-5678",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "abc@gmail.com",
      gender: "female",
      birth: "2002-08-18",
      school: "소프트웨어융합대학",
      majors: {
        main: "컴퓨터공학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: true, 
    },
    answers: [
      { questionId: 1, responseValue: "네트워킹하고 싶어요" },
      { questionId: 2, responseValue: "네트워킹하고 싶어요" },
      { questionId: 3, responseValue: ["Frontend", "Backend"] },
      { questionId: 4, responseValue: ["23-1", "23-2", "24-1"] },
      { questionId: 5, responseValue: "네트워킹하고 싶어요" },
      { questionId: 6, responseValue: ["네트워킹(인맥)", "취업준비를 위한 스터디"] },
      { questionId: 7, responseValue: "네트워킹하고 싶어요" },
      { questionId: 8, responseValue: "네트워킹하고 싶어요" },
    ],
  },
  {
    member: {
      id: 2,
      name: "강명묵",
      grade: 4,
      studentId: 12201674,
      phoneNumber: "010-1234-5678",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "abc@gmail.com",
      gender: "male",
      birth: "2002-08-18",
      school: "소프트웨어융합대학",
      majors: {
        main: "컴퓨터공학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: false, 
    },
    answers: [
      { questionId: 1, responseValue: "네트워킹하고 싶어요" },
      { questionId: 2, responseValue: "네트워킹하고 싶어요" },
      { questionId: 3, responseValue: ["Frontend", "Backend"] },
      { questionId: 4, responseValue: ["23-1", "23-2", "24-1"] },
      { questionId: 5, responseValue: "네트워킹하고 싶어요" },
      { questionId: 6, responseValue: ["네트워킹(인맥)", "취업준비를 위한 스터디"] },
      { questionId: 7, responseValue: "네트워킹하고 싶어요" },
      { questionId: 8, responseValue: "네트워킹하고 싶어요" },
    ],
  },
  {
    member: {
      id: 3,
      name: "정지훈",
      grade: 3,
      studentId: 12204567,
      phoneNumber: "010-2345-6789",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "def@gmail.com",
      gender: "male",
      birth: "2001-03-25",
      school: "소프트웨어융합대학",
      majors: {
        main: "소프트웨어학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: true, 
    },
    answers: [
      { questionId: 1, responseValue: "시작하고 싶어요" },
      { questionId: 2, responseValue: "취업 준비 중" },
      { questionId: 3, responseValue: ["Frontend"] },
      { questionId: 4, responseValue: ["23-1"] },
      { questionId: 5, responseValue: "에브리타임" },
      { questionId: 6, responseValue: ["인맥", "스터디"] },
      { questionId: 7, responseValue: "프론트엔드 기술을 배워보고 싶어요" },
      { questionId: 8, responseValue: "좋은 피드백을 주세요" },
    ],
  },
  {
    member: {
      id: 4,
      name: "박지은",
      grade: 2,
      studentId: 12209876,
      phoneNumber: "010-3456-7890",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "ghi@gmail.com",
      gender: "female",
      birth: "2003-12-10",
      school: "소프트웨어융합대학",
      majors: {
        main: "컴퓨터공학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: false, 
    },
    answers: [
      { questionId: 1, responseValue: "배워보고 싶어요" },
      { questionId: 2, responseValue: "백엔드 기술을 배우고 싶어요" },
      { questionId: 3, responseValue: ["Backend"] },
      { questionId: 4, responseValue: ["23-2"] },
      { questionId: 5, responseValue: "에브리타임" },
      { questionId: 6, responseValue: ["스터디", "기술 향상"] },
      { questionId: 7, responseValue: "백엔드 개발 경험" },
      { questionId: 8, responseValue: "유익한 피드백 부탁드려요" },
    ],
  },
  {
    member: {
      id: 5,
      name: "이수현",
      grade: 3,
      studentId: 12208765,
      phoneNumber: "010-4567-8901",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "jkl@gmail.com",
      gender: "female",
      birth: "2002-07-30",
      school: "소프트웨어융합대학",
      majors: {
        main: "컴퓨터공학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: true, 
    },
    answers: [
      { questionId: 1, responseValue: "프론트엔드에 관심이 있어요" },
      { questionId: 2, responseValue: "기술적인 성장을 원해요" },
      { questionId: 3, responseValue: ["Frontend"] },
      { questionId: 4, responseValue: ["24-1"] },
      { questionId: 5, responseValue: "에브리타임" },
      { questionId: 6, responseValue: ["인맥", "기술 향상"] },
      { questionId: 7, responseValue: "프론트엔드 관련 실무 경험" },
      { questionId: 8, responseValue: "활발한 피드백 부탁드립니다" },
    ],
  },
  {
    member: {
      id: 6,
      name: "홍길동",
      grade: 4,
      studentId: 12213456,
      phoneNumber: "010-5678-1234",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "mno@gmail.com",
      gender: "male",
      birth: "2001-11-02",
      school: "소프트웨어융합대학",
      majors: {
        main: "컴퓨터공학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: false, 
    },
    answers: [
      { questionId: 1, responseValue: "기술을 배우고 싶어요" },
      { questionId: 2, responseValue: "프론트엔드 경험이 필요해요" },
      { questionId: 3, responseValue: ["Frontend"] },
      { questionId: 4, responseValue: ["23-1", "24-1"] },
      { questionId: 5, responseValue: "에브리타임" },
      { questionId: 6, responseValue: ["인맥", "기술 향상"] },
      { questionId: 7, responseValue: "프론트엔드 관련 경험 쌓기" },
      { questionId: 8, responseValue: "기술에 대한 피드백 부탁드립니다" },
    ],
  },
  {
    member: {
      id: 7,
      name: "최하늘",
      grade: 2,
      studentId: 12204589,
      phoneNumber: "010-6789-0123",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "pqr@gmail.com",
      gender: "female",
      birth: "2003-06-15",
      school: "소프트웨어융합대학",
      majors: {
        main: "소프트웨어학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: true, 
    },
    answers: [
      { questionId: 1, responseValue: "배워보고 싶어요" },
      { questionId: 2, responseValue: "프론트엔드 스킬을 키우고 싶어요" },
      { questionId: 3, responseValue: ["Frontend"] },
      { questionId: 4, responseValue: ["23-2"] },
      { questionId: 5, responseValue: "에브리타임" },
      { questionId: 6, responseValue: ["인맥", "스터디"] },
      { questionId: 7, responseValue: "프론트엔드 경험을 쌓고 싶어요" },
      { questionId: 8, responseValue: "좋은 피드백 부탁드립니다" },
    ],
  },
  {
    member: {
      id: 8,
      name: "정세희",
      grade: 3,
      studentId: 12213487,
      phoneNumber: "010-7890-1234",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "stu@gmail.com",
      gender: "female",
      birth: "2002-10-05",
      school: "소프트웨어융합대학",
      majors: {
        main: "컴퓨터공학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: true, 
    },
    answers: [
      { questionId: 1, responseValue: "프론트엔드 관련 기술을 배우고 싶어요" },
      { questionId: 2, responseValue: "기술 스택을 확장하고 싶어요" },
      { questionId: 3, responseValue: ["Frontend"] },
      { questionId: 4, responseValue: ["23-1"] },
      { questionId: 5, responseValue: "에브리타임" },
      { questionId: 6, responseValue: ["인맥", "기술 향상"] },
      { questionId: 7, responseValue: "프론트엔드 기술을 배우고 싶어요" },
      { questionId: 8, responseValue: "좋은 피드백 부탁드립니다" },
    ],
  },
  {
    member: {
      id: 9,
      name: "배지호",
      grade: 2,
      studentId: 12203211,
      phoneNumber: "010-1234-9012",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "uvw@gmail.com",
      gender: "male",
      birth: "2003-01-20",
      school: "소프트웨어융합대학",
      majors: {
        main: "소프트웨어학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: true, 
    },
    answers: [
      { questionId: 1, responseValue: "프론트엔드와 백엔드 모두 관심 있어요" },
      { questionId: 2, responseValue: "프로그래밍 기술을 향상시키고 싶어요" },
      { questionId: 3, responseValue: ["Frontend", "Backend"] },
      { questionId: 4, responseValue: ["24-1"] },
      { questionId: 5, responseValue: "에브리타임" },
      { questionId: 6, responseValue: ["네트워킹", "기술 향상"] },
      { questionId: 7, responseValue: "프론트엔드와 백엔드 모두 배우고 싶어요" },
      { questionId: 8, responseValue: "적극적인 피드백 부탁드려요" },
    ],
  },
  {
    member: {
      id: 10,
      name: "윤지현",
      grade: 4,
      studentId: 12204590,
      phoneNumber: "010-2345-6789",
      nationality: "대한민국",
      nationalityContent: null, 
      email: "xyz@gmail.com",
      gender: "female",
      birth: "2001-05-14",
      school: "소프트웨어융합대학",
      majors: {
        main: "컴퓨터공학과",
        second: ["경영대학", "경영학과"],
      },
      route: "에브리타임", 
      isPayed: true, 
    },
    answers: [
      { questionId: 1, responseValue: "더 많은 사람들과 네트워킹하고 싶어요" },
      { questionId: 2, responseValue: "백엔드 경험을 쌓고 싶어요" },
      { questionId: 3, responseValue: ["Backend"] },
      { questionId: 4, responseValue: ["23-2"] },
      { questionId: 5, responseValue: "에브리타임" },
      { questionId: 6, responseValue: ["기술 향상", "인맥"] },
      { questionId: 7, responseValue: "백엔드 개발 경험을 쌓고 싶어요" },
      { questionId: 8, responseValue: "실질적인 피드백 부탁드립니다" },
    ],
  },
];