export const users = [
  {
    id: 1,
    name: '김소연',
    grade: 4,
    studentID: 12212444,
    nationality: '대한민국',
    email: 'abc@gmail.com',
    gender: 'female',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '컴퓨터공학과',
    second_major: '',
    apply_reason:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod condimentum odio et vulputate. Pellentesque varius vestibulum urna eu congue. Praesent sollicitudin nisl vel odio dignissim, quis ullamcorper sapien fermentum. Donec sagittis, risus ut pulvinar euismod, risus dolor bibendum massa, vel blandit velit leo ut metus. Nulla eu mi dolor. Nunc a consequat ipsum, ut condimentum ipsum. In in nibh et libero eleifend lacinia id a velit. Suspendisse at scelerisque purus, nec commodo ex. Curabitur elementum felis at ante bibendum, et dapibus turpis hendrerit. Cras a volutpat velit. Maecenas dignissim magna a sem dignissim dictum. Fusce at purus vitae quam tempor volutpat. Morbi mollis tortor quis purus dapibus imperdiet.',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '합격',
  },
  {
    id: 2,
    name: '강명묵',
    grade: 4,
    studentID: 12201674,
    nationality: '대한민국',
    email: 'abcabc@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '컴퓨터공학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '합격',
  },
  {
    id: 3,
    name: '박우찬',
    grade: 3,
    studentID: 12220123,
    nationality: '대한민국',
    email: 'park@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '컴퓨터공학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '합격',
  },
  {
    id: 4,
    name: '김철수',
    grade: 4,
    studentID: 12220123,
    nationality: '대한민국',
    email: 'abcabc@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '컴퓨터공학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '합격',
  },
  {
    id: 5,
    name: '김유리',
    grade: 4,
    studentID: 12220123,
    nationality: '대한민국',
    email: 'abcabc@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '인공지능공학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '불합격',
  },
  {
    id: 6,
    name: '김맹구',
    grade: 4,
    studentID: 12220123,
    nationality: '대한민국',
    email: 'abcabc@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '기계공학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '합격',
  },
  {
    id: 7,
    name: '김짱구',
    grade: 4,
    studentID: 12220123,
    nationality: '대한민국',
    email: 'abcabc@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '컴퓨터공학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '불합격',
  },
  {
    id: 8,
    name: '김훈',
    grade: 4,
    studentID: 12220123,
    nationality: '대한민국',
    email: 'abcabc@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '정보통신공학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '합격',
  },
  {
    id: 9,
    name: '박지수',
    grade: 4,
    studentID: 12220123,
    nationality: '대한민국',
    email: 'abcabc@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '경제학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '합격',
  },
  {
    id: 10,
    name: '박철',
    grade: 4,
    studentID: 12220123,
    nationality: '대한민국',
    email: 'abcabc@gmail.com',
    gender: 'male',
    birth: '2002-08-18',
    school: '소프트웨어융합대학',
    major: '컴퓨터공학과',
    second_major: '',
    apply_reason: '네트워킹하고 싶어요',
    interests: ['Frontend', 'Backend'],
    life_and_story: '열심히 살았다',
    gdg_semester: ['23-1', '23-2', '24-1'],
    route: '에브리타임',
    want_to_get: ['네트워킹(인맥)', '취업준비를 위한 스터디'],
    other_activity: '',
    feedback: '',
    //임의로 추가 (합, 불) 일지 (입금, 미입금) 일지 미정
    status: '합격',
  },
];
