const studyDetailData = {
    "statusCode": 200,
    "data": [
        {
            id: 1,
            title: "스마트 컨트랙트 개발",
            simpleIntroduce: "스마트 컨트랙트의 정의와 활용 사례를 배우고, Solidity 언어를 통해 실습합니다.",
            activityIntroduce: "스마트 컨트랙트의 정의와 활용 사례를 배우고, Solidity 언어를 통해 실습합니다.",
            status: "RECRUITING",
            recruitStartDate: "2025-04-01T00:00:00Z",
            recruitEndDate: "2025-04-15T23:59:59Z",
            activityStartDate: "2025-04-01T00:00:00Z",
            activityEndDate: "2025-04-15T23:59:59Z",
            expectedTime: "매주 수요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "GDGOC",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 2,
            title: "NFT와 토큰 이코노미",
            simpleIntroduce: "NFT와 토큰 이코노미의 기본 개념을 배우고, 시장 트렌드를 분석합니다.",
            activityIntroduce: "NFT와 토큰 이코노미의 기본 개념을 배우고, 시장 트렌드를 분석합니다.",
            status: "RECRUITING",
            recruitStartDate: "2025-04-01T00:00:00Z",
            recruitEndDate: "2025-04-15T23:59:59Z",
            activityStartDate: "2025-04-01T00:00:00Z",
            activityEndDate: "2025-04-15T23:59:59Z",
            expectedTime: "매주 목요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "GDGOC",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 3,
            title: "DeFi 개념과 실습",
            simpleIntroduce: "DeFi의 개념과 주요 플랫폼을 배우고, 탈중앙화 금융 시스템을 실습합니다.",
            activityIntroduce: "DeFi의 개념과 주요 플랫폼을 배우고, 탈중앙화 금융 시스템을 실습합니다.",
            status: "RECRUITING",
            recruitStartDate: "2025-04-01T00:00:00Z",
            recruitEndDate: "2025-04-15T23:59:59Z",
            activityStartDate: "2025-04-01T00:00:00Z",
            activityEndDate: "2025-04-15T23:59:59Z",
            expectedTime: "매주 금요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "GDGOC",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 4,
            title: "IPFS와 분산 저장 기술",
            simpleIntroduce: "IPFS와 분산 저장 시스템의 원리를 배우고, 실습을 통해 사용법을 익힙니다.",
            activityIntroduce: "IPFS와 분산 저장 시스템의 원리를 배우고, 실습을 통해 사용법을 익힙니다.",
            status: "RECRUITING",
            recruitStartDate: "2025-04-01T00:00:00Z",
            recruitEndDate: "2025-04-15T23:59:59Z",
            activityStartDate: "2025-04-01T00:00:00Z",
            activityEndDate: "2025-04-15T23:59:59Z",
            expectedTime: "매주 토요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "GDGOC",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 5,
            title: "이더리움 네트워크 분석",
            simpleIntroduce: "이더리움 네트워크의 작동 원리와 주요 기능을 분석하고, 실습을 진행합니다.",
            activityIntroduce: "이더리움 네트워크의 작동 원리와 주요 기능을 분석하고, 실습을 진행합니다.",
            status: "RECRUITING",
            recruitStartDate: "2025-04-01T00:00:00Z",
            recruitEndDate: "2025-04-15T23:59:59Z",
            activityStartDate: "2025-04-01T00:00:00Z",
            activityEndDate: "2025-04-15T23:59:59Z",
            expectedTime: "매주 월요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "PERSONAL",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 6,
            title: "Solidity 프로그래밍 입문",
            simpleIntroduce: "Solidity 언어의 기본 문법과 스마트 컨트랙트 개발을 실습합니다.",
            activityIntroduce: "Solidity 언어의 기본 문법과 스마트 컨트랙트 개발을 실습합니다.",
            status: "RECRUITING",
            recruitStartDate: "2025-04-01T00:00:00Z",
            recruitEndDate: "2025-04-15T23:59:59Z",
            activityStartDate: "2025-04-01T00:00:00Z",
            activityEndDate: "2025-04-15T23:59:59Z",
            expectedTime: "매주 화요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "PERSONAL",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 7,
            title: "웹3.0과 탈중앙화 애플리케이션",
            simpleIntroduce: "웹3.0의 개념과 탈중앙화 애플리케이션(dApp)의 개발 방법을 배웁니다.",
            activityIntroduce: "웹3.0의 개념과 탈중앙화 애플리케이션(dApp)의 개발 방법을 배웁니다.",
            status: "CENCELLED",
            recruitStartDate: "2025-04-01T00:00:00Z",
            recruitEndDate: "2025-04-15T23:59:59Z",
            activityStartDate: "2025-04-01T00:00:00Z",
            activityEndDate: "2025-04-15T23:59:59Z",
            expectedTime: "매주 금요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "PERSONAL",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 8,
            title: "레이어2 솔루션과 확장성",
            simpleIntroduce: "레이어2 솔루션을 통해 블록체인의 확장성과 성능을 향상시키는 방법을 배웁니다.",
            activityIntroduce: "레이어2 솔루션을 통해 블록체인의 확장성과 성능을 향상시키는 방법을 배웁니다.",
            status: "CENCELLED",
            recruitStartDate: "2025-04-01T00:00:00Z",
            recruitEndDate: "2025-04-15T23:59:59Z",
            activityStartDate: "2025-04-01T00:00:00Z",
            activityEndDate: "2025-04-15T23:59:59Z",
            expectedTime: "매주 토요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "GDGOC",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 9,
            title: "블록체인 보안 및 해킹 사례",
            simpleIntroduce: "블록체인 보안 위협과 해킹 사례를 분석하고, 보안 강화 방법을 배웁니다.",
            activityIntroduce: "블록체인 보안 위협과 해킹 사례를 분석하고, 보안 강화 방법을 배웁니다.",
            status: "RECRUITED",
            recruitStartDate: "2025-03-01T00:00:00Z",
            recruitEndDate: "2025-03-15T23:59:59Z",
            activityStartDate: "2025-03-01T00:00:00Z",
            activityEndDate: "2025-03-15T23:59:59Z",
            expectedTime: "매주 월요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "PERSONAL",
            imagePath: "/src/images/google_icon.png"
        },
        {
            id: 10,
            title: "DAO와 거버넌스 모델",
            simpleIntroduce: "DAO의 개념과 거버넌스 모델을 배우고, 실제 구현 방법을 실습합니다.",
            activityIntroduce: "DAO의 개념과 거버넌스 모델을 배우고, 실제 구현 방법을 실습합니다.",
            status: "RECRUITED",
            recruitStartDate: "2025-03-01T00:00:00Z",
            recruitEndDate: "2025-03-15T23:59:59Z",
            activityStartDate: "2025-03-01T00:00:00Z",
            activityEndDate: "2025-03-15T23:59:59Z",
            expectedTime: "매주 수요일 오후 7시 - 9시",
            expectedPlace: "온라인 (Google Meet)",
            type: "GDGOC",
            imagePath: "/src/images/google_icon.png"
        }
    ],
    "message": "요청이 성공적으로 처리되었습니다.",
    "success": true
}

export default studyDetailData;