name: CI/CD Pipeline with CodeDeploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Zip project
      run: zip -r app.zip . -x "*.git*"

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
        SOURCE_DIR: './'

    - name: Deploy to CodeDeploy using AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
      run: |
        aws deploy create-deployment \
          --application-name gdgoc-fe-app \
          --deployment-group-name gdgoc-fe-dg \
          --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=app.zip \
          --file-exists-behavior OVERWRITE

