name: Build Docker and Upload to S3

on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to DockerHub (Optional)
      run: echo "Skipping DockerHub login since we're saving as tar."

    - name: Docker Build
      run: |
        docker build -t nextjs-app .
        docker save nextjs-app -o nextjs-app.tar

    - name: Upload docker image tar to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
        SOURCE_DIR: './'
