name: CI/CD Pipeline with CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Zip project
      run: zip -r app.zip . -x "*.git*"

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
        SOURCE_DIR: './'

    - name: Trigger CodeDeploy
      uses: webfactory/create-aws-codedeploy-deployment@v0.4.0
      with:
        application-name: gdgoc-fe-app
        deployment-group: gdgoc-fe-dg
        deployment-description: "Auto deploy triggered"
        bucket: ${{ secrets.S3_BUCKET }}
        bundle: app.zip
        region: ap-northeast-2
